### PR TITLE
feat: add rating component

### PR DESCRIPTION
**Pull request by sharmayatendra**
# Changes

## rating component added

image

### CODE REVIEW

**Review by tushargoyal812 — COMMENTED** [review]
didn't found any correction.code is clean.
variable names are good.
folder structure is good.looks good to merge

**Review by srv-pranjal — APPROVED** [review]
Great Work. Code is clean.
One suggestion: Try to create a separate commit or branch for updating links in sidebar.

**Review by shlok30 — COMMENTED** [review]
1)Code looks clean

**Review by shlok30 — COMMENTED** [review]
1)Code looks clean
2)You have created separate folders for each component which makes the file structure look very neat

**Review by shlok30 — APPROVED** [review]
You can go ahead and merge it

**Pull request merged**
